work_machine = File.exists?(File.expand_path("~/.workmachine"))

unless work_machine
  cask "arduino"
  cask "blender"
  cask "openscad"
  cask "raspberry-pi-imager"
end

cask "font-hack-nerd-font"
cask "imageoptim"
cask "iterm2"
cask "qmk-toolbox"
cask "visual-studio-code"

brew "mtr"
brew "ngrep"
brew "nmap"
brew "p0f"
brew "pinentry-mac"
