#!/bin/bash

options=(
  style=round
  order=above # undocumented and unsupported https://github.com/FelixKratz/JankyBorders/issues/37#issuecomment-1871262622
  width=3.0
  active_color=0xff00ff00
  inactive_color=0x00000000
  blacklist=iTerm2
)

borders "${options[@]}"

# active_color="gradient(top_left=0xffff00ff,bottom_right=0xff00ddff)"
# active_color=0xffe2e2e3
# inactive_color=0x004145f0
