work_machine = File.exist?(File.expand_path("~/.workmachine"))
server_machine = File.exist?(File.expand_path("~/.servermachine"))

unless server_machine
  mas "WiFi Signal",   id: 525912054

  cask "alfred"
  cask "istat-menus"
  cask "jordanbaird-ice"
  cask "notion"
end

cask "1password"

cask "arc"
cask "bettertouchtool"
cask "hyperkey"
cask "rectangle"
cask "unicodechecker"

unless work_machine || server_machine
  cask "adobe-creative-cloud"
  cask "backblaze"
  cask "ubersicht"
  cask "osquery"
end

brew "ack"
brew "btop"
brew "coreutils"
brew "ctags"
brew "gnu-sed"
brew "graphviz"
brew "iftop"
brew "jq"
brew "mas"
brew "procs"
brew "rg"
brew "switchaudio-osx"
brew "tree"
brew "wget"
brew "yt-dlp"
brew "zenith"
