work_machine = File.exists?(File.expand_path("~/.workmachine"))

tap "homebrew/core"
tap "homebrew/bundle"
tap "buo/cask-upgrade"
tap "dteoh/sqa"

mas "WiFi Signal", id: 525912054
mas "Deliveries",  id: 290986013

cask "1password"
cask "alfred"
cask "bartender"
cask "bettertouchtool"
cask "istat-menus"
cask "karabiner-elements"
cask "notion"
cask "rectangle"
# cask "slowquitapps"
# cask "spotify"
cask "the-unarchiver"
cask "unicodechecker"

unless work_machine
  cask "backblaze"
  cask "ubersicht"
end

brew "ack"
brew "adobe-creative-cloud"
brew "coreutils"
brew "ctags"
brew "gnu-sed"
brew "graphviz"
brew "htop"
brew "iftop"
brew "jq"
brew "mas"
brew "procs"
brew "rg"
brew "trafshow"
brew "tree"
brew "wget"
brew "zenith"
