#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Run system Brewfile and installer first
echo " Checking system apps"
if [ -f ./system/Brewfile ]; then
  brew bundle install --file ./system/Brewfile
fi
if [ -f ./system/install.sh ]; then
  sh -c "${installer}"
fi

echo " Checking topic apps"
# find the Brewfiles and run them iteratively
find . -name Brewfile -depth 2 -not -path "./system/*" | while read brewfile ; do
  brew bundle install --file "$brewfile"
done

# find the installers and run them iteratively
find . -name install.sh -depth 2 -not -path "./system/*" | while read installer ; do
  sh -c "${installer}"
done
