#!/usr/bin/env sh

set -- $(getopt nf "$@")

while true; do
  case $1 in
    -n)
      echo "DRY_RUN"
      DRY_RUN=true; shift; continue
      ;;
    -f)
      FAST_UPDATE=true; shift; continue
      ;;
    --)
      break
      ;;
    *)
      echo "Unknown option \"$1\""
      exit 1
      ;;
  esac
done

set -- "$@"

pushd $ZSH > /dev/null

git_update() {
  git pull --rebase --prune
}

if [ -z "$DRY_RUN" ]; then
  # Check for uncommitted changes
  git diff-index --ignore-submodules --quiet HEAD

  # Run updates or stash+update
  if [ $? = 0 ]; then
    git_update
  else
    git stash
    git_update
    git stash pop
  fi
fi

case $OSTYPE in
  darwin*)
    if [ -z "$DRY_RUN" ] && [ -z "$FAST_UPDATE" ]; then
      echo "» Running installers"
      # Install new packages
      $ZSH/script/install
    fi
    ;;
  linux*)
    ;;
  bsd*)
    ;;
esac

if [ -z "$DRY_RUN" ] && [ -z "$FAST_UPDATE" ]; then
  echo "» Running defaults setup"
  $(dirname "$0")/../osx/set-defaults.sh
fi

popd > /dev/null
