#!/usr/bin/env sh

set -- $(getopt n "$@")

while true; do
  case $1 in
    -n)
      DRY_RUN=true; shift; continue
      ;;
    --)
      break
      ;;
    *)
      echo "Unknown option \"$1\""
      exit 1
      ;;
  esac
done

set -- "$@"

pushd $ZSH > /dev/null

git_update() {
  git pull --rebase --prune
  # git submodule sync
  # git submodule update --init --recursive
}

if [ -z "$DRY_RUN" ]; then
  # Check for uncommitted changes
  git diff-index --ignore-submodules --quiet HEAD

  # Run updates or stash+update
  if [ $? = 0 ]; then
    git_update
  else
    git stash
    git_update
    git stash pop
  fi
fi

case $PLATFORM in
  darwin)
    if [ -z "$DRY_RUN" ]; then
      if command -v rake > /dev/null 2>&1; then
        # Install new packages
        $ZSH/script/install
      fi
    fi
    ;;
  linux)
    ;;
  cygwin)
    ;;
esac

# $(dirname "$0")/relink

# Update Vim Plug
if command -v vim > /dev/null 2>&1; then
  if [ -z "$DRY_RUN" ]; then
    if [ -n "$(git diff HEAD@{1}...HEAD -- vimrc)" ]; then
      vim +PlugInstall +PlugClean +PlugUpgrade +qa
    fi
  fi
fi

popd > /dev/null
